### ISSUE TITLE
Action can't install Waypoint - New release needed ?

### ISSUE THREAD

**Issue by kfh** [hashicorp/action-waypoint#45]
Looks like this issue is hitting me here: https://github.com/hashicorp/action-setup-waypoint/issues/31

Could this be solved by cutting a new release to include the latest changes?

UPDATE: Yep, forked the repo and rebuilt with the latest changes. I'm running this action now in our build/deploy/release pipeline and it works really well.

@pearkes Would appreciate some feedback here. I've been running a forked version since before Christmas now.

**Comment by bondarewicz** [comment]
~@ kfh any chance you could post some instructions? I've forked both `action-setup-waypoint` & `action-waypoint` and currently trying the exact same thing~

EDIT: got it working

**Comment by kfh** [comment]
> ~@ kfh any chance you could post some instructions? I've forked both `action-setup-waypoint` & `action-waypoint` and currently trying the exact same thing~
> 
> EDIT: got it working

Cool. My changes are here: https://github.com/hashicorp/action-waypoint/compare/main...kfh:main

Btw, they are in the process of rewriting Waypoint(server) to be _GitOps_ based so this plugin will probably be obsolete when the next major version is out.

**Comment by bondarewicz** [comment]
just in case #106

**Comment by pearkes** [comment]
Thanks for opening this issue. We wanted to reduce confusion and encourage following what we would suggest is current best practice for using Waypoint with git by archiving this repository.

First, consider using the [native git integration](https://www.waypointproject.io/docs/projects/git). There's more information about how this works on the [0.3 release blog post](https://www.hashicorp.com/blog/announcing-hashicorp-waypoint-0-3-0) for Waypoint.

Alternatively, use the [`action-setup-waypoint`](https://github.com/hashicorp/action-setup-waypoint) action mentioned in the README of this project. This is simpler, more composable (can be used with other actions) and will be more maintainable in the long term if you still wish to use GitHub actions with Waypoint. You could also potentially use that action in conjunction with this one (if you are comfortable forking this Typescript action implementation) and maintain the existing workflow yourself in the longer term, as you are effectively just shelling out to Waypoint from actions.

If those both aren't working for you in an ideal way, please open up an issue on the main GitHub repository and we can problem-solve.

**Comment by pearkes** [comment]
Oh, and @kfh forgot to acknowledge this:

> Btw, they are in the process of rewriting Waypoint(server) to be GitOps based so this plugin will probably be obsolete when the next major version is out.

Definitely, that was the idea. We speculatively used actions prior to that as a kind of example/experiment for integrating into Git/GitHub and ultimately found we wanted a more native experience. That doesn't make using Waypoint in a CI/CD environment like GitHub actions any less relevant or possible – Waypoint is designed for that – but we believe it will feel better in the native way.  We do still document and support generally executing in CI/CD like this.
